<?php

namespace AppBundle\Repository;

/**
 * MagicStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
