<?php

namespace AppBundle\Repository;

/**
 * MagicSpellRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MagicSpellRepository extends \Doctrine\ORM\EntityRepository
{
}
