<?php

namespace AppBundle\Repository;

/**
 * NpcCharacterSheetAnimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NpcCharacterSheetAnimaRepository extends \Doctrine\ORM\EntityRepository
{
}
