<?php

namespace AppBundle\Repository;

/**
 * PlayerCharacterSheetAnimaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerCharacterSheetAnimaRepository extends \Doctrine\ORM\EntityRepository
{
}
