<?php

namespace AppBundle\Repository;

/**
 * PsychicAbilitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychicAbilitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
