<?php

namespace AppBundle\Repository;

/**
 * ResistancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResistancesRepository extends \Doctrine\ORM\EntityRepository
{
}
