<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3orpqpu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3orpqpu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3orpqpu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3orpqpu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3orpqpu\appDevDebugProjectContainer(array(
    'container.build_hash' => '3orpqpu',
    'container.build_id' => '8389a7ab',
    'container.build_time' => 1539156106,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3orpqpu');
